### ISSUE TITLE
Add support for Istio resources

### ISSUE THREAD

**Issue by grebois** [instrumenta/kubeval#80] opened 2018-06-06 13:10 UTC
Considering this resource: 

```
---
apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: default-pipeline-service
spec:
    destination:
      name: default-pipeline-service
    match:
        request:
          headers:
            uri:
              prefix: /api/
    rewrite:
        uri: /
---
```

I get:

```
2 errors occurred:

* Problem loading schema from the network at https://raw.githubusercontent.com/garethr/kubernetes-json-schema/master/master-standalone/routerule.json: Could not read schema from HTTP, response status is 404 Not Found
* Missing a kind key
```

This is the API reference: https://istio.io/docs/reference/config/istio.networking.v1alpha3/

**Comment by ror6ax** [comment] 2018-06-25 12:47
I'd be interested to work on this.

**Comment by garethr** [comment] 2018-08-17 10:50
There are some details in #47 as well. This should just require generating the JSON Schemas from the Istio OpenAPI docs (I use https://github.com/garethr/openapi2jsonschema) and then including them in the right location. If someone can point me at the openapi description for Istio I might be able to add better support for CRDs in kubeval.

**Comment by garethr** [comment] 2018-08-19 17:40
@tmc yes, at least theoretically. The problem there is you can only test against that specific version of the schema, and you need a server running to run the tests - which might be OK depending on your use case.

**Comment by Justin2997** [comment] 2019-01-28 20:53
@garethr Any update on this ? Can I help ?

**Comment by Justin2997** [comment] 2019-02-01 16:15
For people that will like Istio or other CRD like Knative I subject that skip validation for specific apiVersion that you pass to your script before running KubeVal.

**Comment by grzesuav** [comment] 2019-04-12 06:40
hi @garethr , in general it would be useful to have possibility to add additional schemas (alongside k8s one's) - how I can see it, it could be via config file, when location for additional schemas could be placed. What do you think of it ?

My use case :
* we use additional k8s components
* we write own's CRD's


cheers

**Comment by Stono** [comment] 2019-05-21 12:52
So we can't run kubeval if there is a CRD in the `helm template`, it'd be great to add an `--ignore-unknown-apis` or something similar please!

**Comment by garethr** [comment] 2019-07-13 18:21
I'm going to close this as:

1. a duplicate of #47, Istio resources are really just specific custom resources
2. You can now at least ignore missing schemas with `--ignore-missing-schemas` in 0.11.0

**Closed by garethr** 2019-07-13 18:21 UTC
Labels: enhancement
